import { CategoryDef, QuestPadDB } from './types';

export const LS_LANG_KEY = 'wb_pyp_lang';

export const CAT_DEFS: CategoryDef[] = [
  { id: 'cat_study', name: 'Study', nameZh: '学习', color: '#3b82f6', icon: 'book', points: 10, pointName: 'IQ', pointNameZh: '智力', emoji: '🌟' },
  { id: 'cat_money', name: 'Earn Money', nameZh: '赚钱', color: '#f59e0b', icon: 'coin', points: 15, pointName: 'Coin', pointNameZh: '币', emoji: '💰' },
  { id: 'cat_sport', name: 'Sport', nameZh: '运动', color: '#f97316', icon: 'run', points: 12, pointName: 'Energy', pointNameZh: '能量', emoji: '⚡' },
  { id: 'cat_life', name: 'Life', nameZh: '生活', color: '#f43f5e', icon: 'home', points: 8, pointName: 'Care', pointNameZh: '爱心', emoji: '❤️' }
];

export const I18N: Record<string, Record<string, any>> = {
  en: {
    hub_back: "PYP Map",
    app_subtitle: "Daily Quest & Check-in",
    role_kid: "Quest Mode",
    role_parent: "Parent Hub",
    nav_tasks: "Today's Quests",
    nav_goals: "Big Goals",
    nav_rewards: "Reward Vault",
    nav_parent: "Parent Settings",
    month: "Month",
    back_to_cur_month: "Current",
    lock: "Lock",
    locked_back: "Locked. Switched to Quest Mode.",
    sign_in_google: "Sign in with Google",
    sign_in_title: "Welcome to Quest Pad",
    sign_in_desc: "Your personal multi-user task check-in, habit tracker, and celebration system.",
    sign_out: "Sign Out",
    signed_in_as: "Signed in as",
    stay_logged_in_hint: "Stay logged in until sign out · Cloud synced",
    google_only_hint: "Google Login only · Multi-user isolated storage",
    pts_tag: "+{n}",
    completed_badge: "Completed ✓",
    all_done_title: "Quest Accomplished!",
    all_done_sub: "Great inquiry and agency! Take a well-deserved break.",
    time_target: "Target: {min} min",
    time_spent: "Spent: {time}",
    btn_start: "Start Timer",
    btn_done: "Done Step ✓",
    btn_cancel: "Cancel",
    btn_undo_step: "Undo",
    btn_undo_last: "Undo Last Step",
    no_tasks_in_cat: "No quests scheduled in this category today.",
    completed_steps_info: "{done}/{total} steps completed",
    goals_title: "Monthly Inquiry Goals",
    no_goals_set: "No goals set for this month yet.",
    goals_progress: "{done}/{target} accomplished · {steps} total steps",
    pts_balance_title: "Points & Balances Wallet",
    pts_unit: "pts",
    earned_today: "Today +{n}",
    celebration_vault: "Celebration Vault",
    choose_wish_hint: "Choose your reward, then submit for parent approval",
    daily_tier: "Daily",
    weekly_tier: "Weekly",
    monthly_tier: "Monthly",
    no_rewards_tier: "No rewards listed in this tier yet.",
    request_reward: "Request Reward",
    not_enough_stars: "Need more points",
    period_limit: "Limit reached",
    unlimited: "Unlimited",
    left_quota: "{n} left this period",
    needs_stars: "Cost: {cost} · Balance: {bal}",
    my_requests: "My Reward Requests",
    no_requests: "No reward requests yet.",
    status_approved: "Approved",
    status_rejected: "Declined",
    status_pending: "Awaiting Parent",
    parent_overview: "Today's Overview · {date}",
    pending_approvals: "Reward Requests Awaiting Approval",
    approve: "Approve",
    reject: "Decline",
    no_pending: "All clear! No pending reward requests.",
    manage_quests: "Manage Daily Quests",
    new_quest: "New Quest",
    manage_goals: "Manage Monthly Goals",
    new_goal: "New Goal",
    backup_data: "Backup & Restore",
    export_json: "Export JSON",
    import_json: "Import JSON",
    reset_demo: "Reset to Demo",
    clear_all: "Clear All Data",
    change_pin: "Change Parent PIN",
    parent_tab_tasks: "Tasks & Steps",
    parent_tab_goals: "Big Goals",
    parent_tab_points: "Point System",
    parent_tab_rewards: "Reward Vault",
    parent_tab_settings: "PIN & Backup",
    add_new_task: "+ Add Quest",
    add_new_goal: "+ Add Goal",
    add_new_reward: "+ Add Reward",
    adjust_points: "+/- Adjust Points",
    scoring_mode: "Scoring Mode",
    mode_per_step: "Every step earns points (per-step)",
    mode_on_complete: "Entire task must be complete (all-at-once)",
    mode_hint: "Task points are divided evenly across steps. Remainder goes to the last step.",
    category_default_points: "Category Points & Balances",
    manual_adjust_title: "Manual Points Adjustment",
    recent_ledger: "Points Transaction Ledger",
    recent_earned_pts: "Points Earned Records (Latest 30)",
    recent_earned_pts_desc: "Latest 30 quest steps completed and points awarded",
    no_earned_pts: "No points earned yet. Complete daily quest steps to start earning inquiry points!",
    pts_earned_badge: "+{n}",
    col_points: "Points",
    col_category: "Category",
    col_time: "Time",
    col_quest_step: "Quest & Step",
    task_title: "Quest Title",
    task_cat: "Category",
    task_pts: "Reward Amount",
    task_goal: "Associated Big Goal",
    no_goal_assoc: "None (Standalone Quest)",
    task_days: "Repeat on Days",
    task_steps: "Sub-steps (completed in order)",
    step_minutes_hint: "min",
    add_step: "+ Add Step",
    step_name_placeholder: "Step description (e.g. Read 10 pages)",
    goal_title: "Goal Title",
    goal_desc: "Encouragement / Notes",
    goal_month: "Target Month",
    task_months: "Target Months",
    task_months_multi: "Multi-select",
    month_select_all: "All Year",
    month_cur_only: "This Month",
    months_selected_count: "months selected",
    at_least_one_month: "Please select at least one month",
    goal_target: "Target Completion Count",
    reward_name: "Reward Name",
    reward_cost: "Point Cost",
    reward_cat: "Deduct From Category",
    cat_iso_hint: "Points earned from different categories cannot be interchanged. Choose which category will be deducted for this reward.",
    reward_limit: "Period Limit (0 = Unlimited)",
    reward_tier: "Tier",
    reward_desc: "Notes / Details",
    child_name: "Child's Name",
    change_pin_btn: "Change PIN",
    status_active: "Active",
    status_inactive: "Paused",
    toggle_active: "Pause / Resume",
    del_task_confirm: "Delete this quest? Points already earned remain in ledger.",
    del_goal_confirm: "Delete this goal? Associated quests will be preserved.",
    del_reward_confirm: "Delete this reward from vault?",
    adjust_cat: "Category",
    adjust_delta: "Amount (+ to reward, - to deduct)",
    adjust_reason: "Reason / Note (e.g. Extra chore, Good agency)",
    saved_toast: "Saved successfully!",
    deleted_toast: "Deleted.",
    pin_new: "New 4-Digit PIN",
    pin_confirm: "Confirm 4-Digit PIN",
    pin_changed: "PIN updated successfully!",
    pin_mismatch: "PINs do not match.",
    modal_cancel: "Cancel",
    modal_save: "Save",
    pin_enter: "Parent Access PIN",
    pin_hint: "Enter 4-digit PIN (Default: 1234)",
    pin_wrong: "Incorrect PIN. Please try again.",
    pin_unlocked: "Parent Hub unlocked!",
    modal_confirm: "Confirm",
    days_short: ["Sun","Mon","Tue","Wed","Thu","Fri","Sat"]
  },
  zh: {
    hub_back: "探究主页",
    app_subtitle: "每日探究与打卡",
    role_kid: "探究打卡",
    role_parent: "家长后台",
    nav_tasks: "今日任务",
    nav_goals: "探究目标",
    nav_rewards: "心愿兑换",
    nav_parent: "家长后台",
    month: "月份",
    back_to_cur_month: "本月",
    lock: "锁定",
    locked_back: "已锁定，回到打卡端。",
    sign_in_google: "使用 Google 账号登录",
    sign_in_title: "欢迎使用 Quest Pad 打卡台",
    sign_in_desc: "多用户云端打卡、习惯培养、目标管理与心愿奖励系统。",
    sign_out: "退出登录",
    signed_in_as: "已登录：",
    stay_logged_in_hint: "保持登录直到手动退出 · 云端 Firestore 实时同步",
    google_only_hint: "仅支持 Google 登录 · 多用户数据隔离",
    pts_tag: "+{n}",
    completed_badge: "全部完成 ✓",
    all_done_title: "恭喜！任务全部完成！",
    all_done_sub: "自主探究行动力太棒了！快去休息与自由探索吧！",
    time_target: "建议：{min} 分钟",
    time_spent: "用时：{time}",
    btn_start: "开始计时",
    btn_done: "完成本步 ✓",
    btn_cancel: "取消",
    btn_undo_step: "撤销",
    btn_undo_last: "撤销最后一步",
    no_tasks_in_cat: "该分类今天没有安排任务，好好休息吧！",
    completed_steps_info: "已完成 {done}/{total} 步",
    goals_title: "月度探究目标",
    no_goals_set: "本月还没有设置目标。",
    goals_progress: "已完成 {done}/{target} 次 · 累计 {steps} 步",
    calendar_title: "月度打卡日历",
    pts_balance_title: "各分类积分与结余",
    pts_unit: "分",
    earned_today: "今日 +{n}",
    celebration_vault: "心愿兑换屋",
    choose_wish_hint: "选好心愿奖励，提交给家长确认",
    daily_tier: "每日",
    weekly_tier: "每周",
    monthly_tier: "每月",
    no_rewards_tier: "这一档还没有奖励。",
    request_reward: "申请兑换",
    not_enough_stars: "积分不足",
    period_limit: "本期已达上限",
    unlimited: "不限次",
    left_quota: "本期还可换 {n} 次",
    needs_stars: "消耗 {cost} · 结余 {bal}",
    my_requests: "我的心愿申请",
    no_requests: "暂无申请记录。",
    status_approved: "已通过",
    status_rejected: "未通过",
    status_pending: "等家长确认",
    parent_overview: "今日概览 · {date}",
    pending_approvals: "待确认的心愿兑换",
    approve: "通过并扣分",
    reject: "驳回",
    no_pending: "暂无待确认申请。",
    manage_quests: "管理每日任务",
    new_quest: "新增任务",
    manage_goals: "管理月度目标",
    new_goal: "新增目标",
    backup_data: "数据备份与恢复",
    export_json: "导出 JSON 备份",
    import_json: "导入恢复",
    reset_demo: "重置为示例",
    clear_all: "清空全部数据",
    change_pin: "修改家长密码",
    parent_tab_tasks: "任务与步骤",
    parent_tab_goals: "月度目标",
    parent_tab_points: "积分与规则",
    parent_tab_rewards: "兑换管理",
    parent_tab_settings: "密码与数据",
    add_new_task: "+ 新增任务",
    add_new_goal: "+ 新增目标",
    add_new_reward: "+ 新增心愿",
    adjust_points: "+/- 奖惩积分",
    scoring_mode: "计分规则",
    mode_per_step: "每完成一步就得该步积分",
    mode_on_complete: "整个任务全部完成才给分",
    mode_hint: "任务积分会自动平摊到各个步骤，余数归最后一步。",
    category_default_points: "分类默认分值与结余",
    manual_adjust_title: "手动调整积分",
    recent_ledger: "积分明细流水",
    recent_earned_pts: "已获积分明细（最新30条）",
    recent_earned_pts_desc: "展示最新完成任务并获得的 30 条积分流水记录",
    no_earned_pts: "暂无积分获得记录。完成每日任务步骤即可开始积累探究积分！",
    pts_earned_badge: "+{n}",
    col_points: "获得积分",
    col_category: "所属分类",
    col_time: "获得时间",
    col_quest_step: "任务与步骤",
    task_title: "任务名称",
    task_cat: "所属分类",
    task_pts: "奖励积分",
    task_goal: "关联月度目标",
    no_goal_assoc: "不关联目标",
    task_days: "每周哪几天要做",
    task_steps: "步骤拆解（孩子按顺序打卡）",
    step_minutes_hint: "分钟",
    add_step: "+ 添加步骤",
    step_name_placeholder: "步骤名称（如 读课文10页）",
    goal_title: "目标名称",
    goal_desc: "给孩子的鼓励与说明",
    goal_month: "目标月份",
    task_months: "适用月份",
    task_months_multi: "支持多选",
    month_select_all: "全年12个月",
    month_cur_only: "仅当月",
    months_selected_count: "个适用月份",
    at_least_one_month: "请至少选择一个适用月份",
    goal_target: "目标完成次数",
    reward_name: "心愿名称",
    reward_cost: "消耗积分",
    reward_cat: "从哪个分类扣分",
    cat_iso_hint: "不同分类赚取的积分不能通用。请选择兑换此心愿将扣除哪一个分类的专属积分。",
    reward_limit: "周期次数上限（0表示不限）",
    reward_tier: "所属档位",
    reward_desc: "心愿备注",
    child_name: "孩子名字",
    change_pin_btn: "修改密码",
    status_active: "进行中",
    status_inactive: "已暂停",
    toggle_active: "启用/暂停",
    del_task_confirm: "确定删除此任务吗？已获得的积分将保留在流水中。",
    del_goal_confirm: "确定删除该目标吗？关联的任务会保留为独立任务。",
    del_reward_confirm: "确定删除该心愿兑换项吗？",
    adjust_cat: "选择分类",
    adjust_delta: "增加/扣减积分（如 +20 或 -15）",
    adjust_reason: "奖惩原因（如 帮忙做家务）",
    saved_toast: "保存成功！",
    deleted_toast: "已删除。",
    pin_new: "新 4 位密码",
    pin_confirm: "再次输入确认",
    pin_changed: "密码修改成功！",
    pin_mismatch: "两次输入的密码不一致。",
    modal_cancel: "取消",
    modal_save: "保存",
    pin_enter: "输入家长密码",
    pin_hint: "请输入 4 位密码（默认 1234）",
    pin_wrong: "密码错误，请重试。",
    pin_unlocked: "已进入家长后台！",
    modal_confirm: "确认",
    days_short: ["日","一","二","三","四","五","六"]
  }
};

export const ENCOURAGING_PHRASES = {
  en: [
    "Awesome Job! You're a superstar! 🌟",
    "Mission Accomplished! Keep shining! 🚀",
    "Fantastic inquiry and great agency! 🎉",
    "You crushed it! Super proud of you! 💪",
    "Level up! Brilliant effort today! ✨",
    "Quest Master! Well-deserved break! 🏆",
    "Unstoppable energy! High five! ⚡",
    "Bullseye! You reached your goal! 🎯"
  ],
  zh: [
    "太棒了！今天也是闪闪发光的小英雄！🌟",
    "任务圆满达成！自律的孩子最帅气！🚀",
    "哇！太厉害啦！为你的专注点赞！🎉",
    "超级棒！继续保持这份热情与好奇！💪",
    "探究力拉满！今天又成长了一大步！✨",
    "达成成就！享受属于你的高光时刻吧！🏆",
    "活力充沛！行动力满分！⚡",
    "完美收官！休息一下继续出发！🎯"
  ]
};
